"""add users and refresh_tokens tables

Revision ID: 0001
Revises:
Create Date: 2026-07-07 10:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="用户ID"),
        sa.Column("username", sa.String(length=64), nullable=False, comment="用户名"),
        sa.Column(
            "password_hash",
            sa.String(length=256),
            nullable=False,
            comment="bcrypt 密码哈希",
        ),
        sa.Column(
            "email",
            sa.String(length=128),
            nullable=False,
            server_default="",
            comment="邮箱地址",
        ),
        sa.Column(
            "role",
            sa.Enum("admin", "auditor", name="userrole"),
            nullable=False,
            server_default="auditor",
            comment="角色：admin / auditor",
        ),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", "pending", name="userstatus"),
            nullable=False,
            server_default="pending",
            comment="状态：active / disabled / pending",
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=256),
            nullable=False,
            server_default="",
            comment="头像URL",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Token ID"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="关联用户ID"),
        sa.Column(
            "token_hash",
            sa.String(length=256),
            nullable=False,
            comment="SHA-256 哈希后的 refresh token",
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="过期时间（7天）"),
        sa.Column(
            "revoked",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
            comment="是否已撤销",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
