"""add missing tables and user login lock columns

Adds document, page, paragraph, element, library, resource, format_template,
rule, and audit result tables that were not included in the initial migration.
Also adds users.failed_login_attempts and users.locked_until columns and
makes users/refresh_tokens created_at/updated_at non-nullable.

Revision ID: c8fd52a7316a
Revises: 0001
Create Date: 2026-07-14 19:38:53.902449

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8fd52a7316a'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False, comment='文件所属用户的id值'),
    sa.Column('doc_id', sa.String(length=512), nullable=False, comment='文件的内容的md5值'),
    sa.Column('total_page_num', sa.Integer(), nullable=False, comment='文件总页数'),
    sa.Column('save_path', sa.String(length=512), nullable=False, comment='保存路径'),
    sa.Column(
        'reconstructed_path', sa.String(length=512), nullable=True,
        comment='重建/转换后的docx MinIO存储路径'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('imported_to_resource', sa.Boolean(), nullable=False, comment='是否已导入资源库'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('format_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='公文类型'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为该文种默认模板'),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, comment='是否为系统内置模板（不可删除）'),
    sa.Column('content', sa.JSON(), nullable=False, comment='模板内容（JSON）'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('librarys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=512), nullable=False, comment='文档的uuid'),
    sa.Column('doc_name', sa.String(length=512), nullable=False, comment='文件名称'),
    sa.Column('total_page_num', sa.Integer(), nullable=False, comment='文档的总页数'),
    sa.Column('page_no', sa.Integer(), nullable=False, comment='当前页的页码'),
    sa.Column('block_no', sa.Integer(), nullable=False, comment='当前文本所属的块'),
    sa.Column('block_text', sa.String(length=4096), nullable=False, comment='当前文本块内容'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_domain',
    sa.Column('id', sa.String(length=20), nullable=False, comment='领域ID（如GOV、AUD等）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='领域名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='领域描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='存储路径'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column(
        'domain_id', sa.String(length=20), nullable=True,
        comment='所属领域ID（如GOV、AUD等）'),
    sa.Column(
        'status', sa.String(length=20), nullable=False,
        comment='状态：uploaded, processed, failed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_file_id'), 'rule_file', ['id'], unique=False)
    op.create_table('content_audit_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False),
    sa.Column('domain_name', sa.String(length=100), nullable=False, comment='领域名称'),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column(
        'violations_json', sa.Text(), nullable=False,
        comment='JSON: [{rule_id, violat_dsc, origin_text, severity, cor_suggest, domain_name}]'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correction_audit_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False),
    sa.Column('correction_count', sa.Integer(), nullable=False),
    sa.Column(
        'corrections_json', sa.Text(), nullable=False,
        comment='JSON: [{source, target, errors}]'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('format_audit_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment="公文类型，如'通知'"),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column(
        'errors_json', sa.Text(), nullable=False,
        comment='JSON: [{block_name, block_no, error_type, details, page_no}]'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='所属文档ID'),
    sa.Column('page_no', sa.Integer(), nullable=False, comment='页码'),
    sa.Column('save_path', sa.String(length=512), nullable=False, comment='保存路径'),
    sa.Column('raw', mysql.LONGBLOB(), nullable=True, comment='原始内容'),
    sa.Column('top_margin', sa.Float(), nullable=False, comment='上边距'),
    sa.Column('bottom_margin', sa.Float(), nullable=False, comment='下边距'),
    sa.Column('left_margin', sa.Float(), nullable=False, comment='左边距'),
    sa.Column('right_margin', sa.Float(), nullable=False, comment='右边距'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plagiarism_audit_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False),
    sa.Column('is_plagiarism', sa.Boolean(), nullable=False),
    sa.Column('max_similarity', sa.Float(), nullable=False),
    sa.Column('dynamic_threshold', sa.Float(), nullable=False),
    sa.Column('matched_doc_index', sa.Integer(), nullable=False),
    sa.Column('matched_substring_length', sa.Integer(), nullable=False),
    sa.Column('matched_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False, comment='标题'),
    sa.Column('author', sa.String(length=256), nullable=True, comment='作者'),
    sa.Column('source', sa.String(length=256), nullable=True, comment='来源'),
    sa.Column('tags', sa.String(length=1024), nullable=True, comment='标签，逗号分隔'),
    sa.Column('publish_date', sa.Date(), nullable=True, comment='发布日期'),
    sa.Column('file_type', sa.String(length=32), nullable=False, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('minio_path', sa.String(length=512), nullable=False, comment='MinIO 对象路径'),
    sa.Column('md5', sa.String(length=64), nullable=False, comment='文件 MD5'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='切片数量'),
    sa.Column('char_count', sa.Integer(), nullable=False, comment='总字符数'),
    sa.Column(
        'status', sa.String(length=32), nullable=False,
        comment='状态：ready / processing / error'),
    sa.Column(
        'resource_type', sa.String(length=32), nullable=False,
        comment='资源类型：manual / original / annotated'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='关联文档 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='规则名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则描述'),
    sa.Column('pattern', sa.Text(), nullable=False, comment='规则模式（正则表达式或其他格式）'),
    sa.Column(
        'severity', sa.String(length=20), nullable=False,
        comment='严重程度：error, warning, info'),
    sa.Column(
        'domain_id', sa.String(length=20), nullable=False,
        comment='所属领域ID（如GOV、AUD等）'),
    sa.Column('rule_file_id', sa.Integer(), nullable=True, comment='来源文件'),
    sa.Column('is_manual', sa.Boolean(), nullable=False, comment='是否手动添加'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['rule_file_id'], ['rule_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_id'), 'rule', ['id'], unique=False)
    op.create_table('writing_style_audit_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=512), nullable=False),
    sa.Column('notif_type', sa.String(length=50), nullable=False, comment='通知类型'),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False, comment='JSON: 错误字符串列表'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False, comment='所属页面ID'),
    sa.Column(
        'section_type',
        sa.Enum(
            'header_copy_number', 'header_classification_duration', 'header_urgency_level',
            'header_issuing_logo', 'header_issuing_number', 'header_signatory',
            'header_ruling_line_pos', 'body_title', 'body_addressee', 'body_main_text',
            'body_attachment_note', 'body_issuing_signature', 'body_issue_date', 'body_stamp',
            'body_note', 'body_attachments', 'footer_closing_line', 'footer_carbon_copy',
            'footer_issuing_office', 'footer_distribution_date', 'footer_page_number'),
        nullable=False,
        comment='段落类型'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='同一类型内的顺序'),
    sa.Column('space_before', sa.Float(), nullable=False, comment='段前间距'),
    sa.Column('space_after', sa.Float(), nullable=False, comment='段后间距'),
    sa.Column('line_spacing', sa.Float(), nullable=False, comment='行距'),
    sa.Column('first_indent', sa.Float(), nullable=False, comment='首行缩进'),
    sa.Column('left_indent', sa.Float(), nullable=False, comment='文本之前缩进(pt)'),
    sa.Column('right_indent', sa.Float(), nullable=False, comment='文本之后缩进(pt)'),
    sa.Column('block_no', sa.Integer(), nullable=False, comment='块序号'),
    sa.Column(
        'outline_level',
        sa.Enum('heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'body_text', 'others'),
        nullable=False,
        comment='大纲等级'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False, comment='所属段落ID'),
    sa.Column('x0', sa.Float(), nullable=False, comment='左上角x坐标'),
    sa.Column('y0', sa.Float(), nullable=False, comment='左上角y坐标'),
    sa.Column('x1', sa.Float(), nullable=False, comment='右下角x坐标'),
    sa.Column('y1', sa.Float(), nullable=False, comment='右下角y坐标'),
    sa.Column('font_family', sa.String(length=255), nullable=False, comment='字体'),
    sa.Column('font_size', sa.Float(), nullable=False, comment='字号'),
    sa.Column('font_weight', sa.Boolean(), nullable=False, comment='是否加粗'),
    sa.Column('font_style', sa.Boolean(), nullable=False, comment='是否倾斜'),
    sa.Column('text', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='行号'),
    sa.Column('exist', sa.Boolean(), nullable=False, comment='是否存在'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Backfill any NULL timestamp values before switching to non-nullable.
    # The initial migration created these columns as nullable, but the ORM
    # models declare them as required.
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE users SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE refresh_tokens SET created_at = NOW() WHERE created_at IS NULL")

    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
    op.add_column(
        'users',
        sa.Column(
            'failed_login_attempts', sa.Integer(), server_default=sa.text('0'),
            nullable=False, comment='连续登录失败次数'))
    op.add_column(
        'users',
        sa.Column('locked_until', sa.DateTime(), nullable=True, comment='账户锁定到期时间'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')
    op.drop_table('elements')
    op.drop_table('paragraphs')
    op.drop_table('writing_style_audit_results')
    op.drop_index(op.f('ix_rule_id'), table_name='rule')
    op.drop_table('rule')
    op.drop_table('resources')
    op.drop_table('plagiarism_audit_results')
    op.drop_table('pages')
    op.drop_table('format_audit_results')
    op.drop_table('correction_audit_results')
    op.drop_table('content_audit_results')
    op.drop_index(op.f('ix_rule_file_id'), table_name='rule_file')
    op.drop_table('rule_file')
    op.drop_table('rule_domain')
    op.drop_table('librarys')
    op.drop_table('format_templates')
    op.drop_table('documents')
    # ### end Alembic commands ###
