[project]
name = "courtier-plugin-text-correction"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "courtier-plugin-sdk",
    "doccorrector",
]

[tool.uv.sources]
courtier-plugin-sdk = { path = "../../../../libs/shared/plugin_sdk", editable = true }
doccorrector = { path = "../../../../libs/docaudit/doccorrector", editable = true }
